[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies", "node_modules"]
fs_permissions = [{ access = "read-write", path = "../" }]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.0.1"
cartesi-rollups-contracts = "2.0.0"
vlayer = "1.2.0"
risc0-ethereum = { version = "2.1.1", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.1.1-soldeer/contracts.zip" }

[soldeer]
remappings_generate = false
remappings_regenerate = false
